root = "."
tmp_dir = "tmp"

[build]
# Pre-command for building wasm
pre_cmd = ["GOOS=js GOARCH=wasm go build -o ./showcase/web/app.wasm ./showcase/"]
# Command to build and run the showcase app
cmd = "go build -o ./showcase/tmp/main ./showcase/"
bin = "./showcase/tmp/main"
include_ext = ["go", "css"]
exclude_dir = ["tmp"]
exclude_file = []
delay = 1000
stop_on_error = true
send_interrupt = false
kill_delay = 500
