// This file is generated by the generate_components.py script
// Do not edit this file manually

package sp

import "github.com/maxence-charriere/go-app/v10/pkg/app"

// spectrumStyles represents an  component
type spectrumStyles struct {
	app.Compo
	*styler[*spectrumStyles]
	*classer[*spectrumStyles]
	*ider[*spectrumStyles]

	// Properties

}

// IStyles is the interface for  component methods
type IStyles interface {
	app.UI
	Styler[IStyles]
	Classer[IStyles]
	Ider[IStyles]
}

// Styles CSS Custom Properties that Power the various color and size themes defined by Spectrum CSS. These properties can be accessed directly or through THE sp-theme element.
func Styles() IStyles {
	element := &spectrumStyles{}

	element.styler = newStyler(element)
	element.classer = newClasser(element)
	element.ider = newIder(element)

	return element
}

// Style sets a style property with a value
func (c *spectrumStyles) Style(key, format string, values ...any) IStyles {
	return c.styler.Style(key, format, values...)
}

// Styles sets multiple style properties
func (c *spectrumStyles) Styles(styles map[string]string) IStyles {
	return c.styler.Styles(styles)
}

// Class adds a class to the element
func (c *spectrumStyles) Class(class string) IStyles {
	return c.classer.Class(class)
}

// Classes adds multiple classes to the element
func (c *spectrumStyles) Classes(classes ...string) IStyles {
	return c.classer.Classes(classes...)
}

// Id sets the id of the element
func (c *spectrumStyles) Id(id string) IStyles {
	return c.ider.Id(id)
}

// Render renders the  component
func (c *spectrumStyles) Render() app.UI {
	element := app.Elem("")

	// Set attributes

	// Apply styles, classes, and id
	element = element.Styles(c.styler.styles)

	// Apply classes if any
	if len(c.classer.classes) > 0 {
		element = element.Class(c.classer.classes...)
	}

	// Apply id if set
	if c.ider.id != "" {
		element = element.ID(c.ider.id)
	}

	return element
}
