// This file is generated by the generate_components.py script
// Do not edit this file manually

package sp

import "github.com/maxence-charriere/go-app/v10/pkg/app"

// spectrumSidenavHeading represents an sp-sidenav-heading component
type spectrumSidenavHeading struct {
	app.Compo
	*styler[*spectrumSidenavHeading]
	*classer[*spectrumSidenavHeading]
	*ider[*spectrumSidenavHeading]

	// Properties
	// The text label for the heading
	PropLabel string

	// Content for default slot
	PropBody []app.UI

	// Content slots

}

// ISidenavHeading is the interface for sp-sidenav-heading component methods
type ISidenavHeading interface {
	app.UI
	Styler[ISidenavHeading]
	Classer[ISidenavHeading]
	Ider[ISidenavHeading]
	Label(string) ISidenavHeading

	Body(...app.UI) ISidenavHeading
	AddToBody(app.UI) ISidenavHeading
	Text(string) ISidenavHeading
}

// SidenavHeading A non-interactive heading element that groups sp-sidenav-item children under a visible structure in a sidenav component.
func SidenavHeading() ISidenavHeading {
	element := &spectrumSidenavHeading{
		PropLabel: "",
		PropBody:  []app.UI{},
	}

	element.styler = newStyler(element)
	element.classer = newClasser(element)
	element.ider = newIder(element)

	return element
}

// Label The text label for the heading
func (c *spectrumSidenavHeading) Label(label string) ISidenavHeading {
	c.PropLabel = label
	return c
}

// Body sets the content for the default slot
func (c *spectrumSidenavHeading) Body(elements ...app.UI) ISidenavHeading {
	c.PropBody = elements
	return c
}

// AddToBody adds a UI element to the default slot
func (c *spectrumSidenavHeading) AddToBody(element app.UI) ISidenavHeading {
	c.PropBody = append(c.PropBody, element)
	return c
}

// Text sets text content for the default slot
func (c *spectrumSidenavHeading) Text(text string) ISidenavHeading {
	c.PropBody = []app.UI{app.Text(text)}
	return c
}

// Style sets a style property with a value
func (c *spectrumSidenavHeading) Style(key, format string, values ...any) ISidenavHeading {
	return c.styler.Style(key, format, values...)
}

// Styles sets multiple style properties
func (c *spectrumSidenavHeading) Styles(styles map[string]string) ISidenavHeading {
	return c.styler.Styles(styles)
}

// Class adds a class to the element
func (c *spectrumSidenavHeading) Class(class string) ISidenavHeading {
	return c.classer.Class(class)
}

// Classes adds multiple classes to the element
func (c *spectrumSidenavHeading) Classes(classes ...string) ISidenavHeading {
	return c.classer.Classes(classes...)
}

// Id sets the id of the element
func (c *spectrumSidenavHeading) Id(id string) ISidenavHeading {
	return c.ider.Id(id)
}

// Render renders the sp-sidenav-heading component
func (c *spectrumSidenavHeading) Render() app.UI {
	element := app.Elem("sp-sidenav-heading")

	// Set attributes
	if c.PropLabel != "" {
		element = element.Attr("label", c.PropLabel)
	}

	// Add slots and children
	slotElements := []app.UI{}

	// Add content for default slot if specified
	if len(c.PropBody) > 0 {
		slotElements = append(slotElements, c.PropBody...)
	}

	// Add all elements to the component
	if len(slotElements) > 0 {
		element = element.Body(slotElements...)
	}

	// Apply styles, classes, and id
	element = element.Styles(c.styler.styles)

	// Apply classes if any
	if len(c.classer.classes) > 0 {
		element = element.Class(c.classer.classes...)
	}

	// Apply id if set
	if c.ider.id != "" {
		element = element.ID(c.ider.id)
	}

	return element
}
